### ISSUE TITLE
啥时候能出支持win11的版本？

### ISSUE THREAD

**Issue by vbrun-lab** [XMQSVIP/SoEasyPack#1]
啥时候能出支持win11的版本？

**Comment by XMQSVIP** [comment]
理论上是支持win11的，我只是没试过，你可以试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XMQSVIP/SoEasyPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月12日(星期四) 下午2:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[XMQSVIP/SoEasyPack] 啥时候能出支持win11的版本？ (Issue #1)





 
啥时候能出支持win11的版本？
